FROM python:3.8

WORKDIR /galaxy

# copy files
COPY . /galaxy

RUN /galaxy/scripts/common_startup.sh
RUN mkdir -p /galaxy/database/dependencies
RUN . /galaxy/.venv/bin/activate && python ./scripts/manage_tool_dependencies.py init_if_needed

