FROM --platform=amd64 regproxy.ornl.gov/hub_proxy/python:3.10


RUN apt update && apt install -y ffmpeg && curl -fsSL https://get.docker.com -o get-docker.sh && sh ./get-docker.sh

RUN apt-get update && apt-get install -y nodejs npm \
    && corepack enable \
    && corepack prepare pnpm@10.26.1 --activate \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /galaxy

# copy files
COPY . /galaxy

RUN /galaxy/scripts/common_startup.sh
RUN mkdir -p /galaxy/database/dependencies
RUN . /galaxy/.venv/bin/activate && python ./scripts/manage_tool_dependencies.py init_if_needed && pip install rucio-clients==40.2.0

