name: Client Unit Testing
on:
  push:
    paths:
      - 'client/**'
  pull_request:
    paths:
      - 'client/**'
concurrency:
  group: client-${{ github.ref }}
  cancel-in-progress: true
jobs:
  client-unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node}}
        cache: 'yarn'
        cache-dependency-path: 'client/yarn.lock'
    - run: yarn install --frozen-lockfile
      working-directory: client
    - name: Stage client libs (Gulp)
      run: yarn run gulp client
      working-directory: client
    - name: Run Unit Tests
      run: yarn run qunit
      working-directory: client
    - run: yarn jest
      working-directory: client
