name: macOS startup
on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'lib/galaxy_test/selenium/**'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'lib/galaxy_test/selenium/**'
concurrency:
  group: osx-first-startup-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Startup test
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
      with:
        path: 'galaxy root'
    - name: Get full Python version
      id: full-python-version
      shell: bash
      run: echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")
    - name: Cache pip dir
      uses: actions/cache@v1
      id: pip-cache
      with:
        path: ~/Library/Caches/pip
        # scripts/common_startup.sh creates a conda env for Galaxy containing Python 3.7
        key: pip-cache-3.7-${{ hashFiles('galaxy root/requirements.txt') }}
    - name: Cache tox env
      uses: actions/cache@v2
      with:
        path: .tox
        key: tox-cache-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('galaxy root/requirements.txt') }}-osx
    - name: Install and activate miniconda  # use this job to test using Python from a conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: ''
    - name: Install tox
      run: pip install tox
    - name: run tests
      run: tox -e first_startup
      working-directory: 'galaxy root'
