name: Selenium tests (beta history panel)
on:
  push:
    paths-ignore:
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'doc/**'
env:
  GALAXY_CONFIG_GALAXY_URL_PREFIX: '/galaxypf'
  GALAXY_TEST_DBURI: 'postgresql://postgres:postgres@localhost:5432/galaxy?client_encoding=utf8'
  GALAXY_TEST_RAISE_EXCEPTION_ON_HISTORYLESS_HDA: '1'
  GALAXY_TEST_SELENIUM_RETRIES: 1
  GALAXY_TEST_SELENIUM_BETA_HISTORY: 1
  GALAXY_TEST_SKIP_FLAKEY_TESTS_ON_ERROR: 1
  YARN_INSTALL_OPTS: --frozen-lockfile
  GALAXY_CONFIG_SQLALCHEMY_WARN_20: '1'
concurrency:
  group: selenium-beta-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7']
        chunk: [0, 1, 2]
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'galaxy root'
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Get full Python version
        id: full-python-version
        shell: bash
        run: echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")
      - name: Cache pip dir
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ matrix.python-version }}-${{ hashFiles('galaxy root/requirements.txt') }}
      - name: Cache galaxy venv
        uses: actions/cache@v2
        with:
          path: .venv
          key: gxy-venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('galaxy root/requirements.txt') }}-selenium-beta
      - uses: mvdbeek/gha-yarn-cache@master
        with:
          yarn-lock-file: 'galaxy root/client/yarn.lock'
      - uses: nanasess/setup-chromedriver@master
      - name: Run tests
        run: ./run_tests.sh -selenium lib/galaxy_test/selenium -- --num-shards=3 --shard-id=${{ matrix.chunk }}
        working-directory: 'galaxy root'
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Selenium beta history panel test results (${{ matrix.python-version }}, ${{ matrix.chunk }})
          path: 'galaxy root/run_selenium_tests.html'
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Selenium beta history panel debug info (${{ matrix.python-version }}, ${{ matrix.chunk }})
          path: 'galaxy root/database/test_errors'
