name: Unit tests
on:
  push:
    paths-ignore:
      - 'client/**'
      - 'doc/**'
      - 'lib/galaxy_test/selenium/**'
  pull_request:
    paths-ignore:
      - 'client/**'
      - 'doc/**'
      - 'lib/galaxy_test/selenium/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.11']
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'galaxy root'
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'
          cache: 'yarn'
          cache-dependency-path: 'galaxy root/client/yarn.lock'
      - name: Get full Python version
        id: full-python-version
        shell: bash
        run: echo "version=$(python -c 'import sys; print("-".join(str(v) for v in sys.version_info))')" >> $GITHUB_OUTPUT
      - name: Cache pip dir
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ matrix.python-version }}-${{ hashFiles('galaxy root/requirements.txt') }}
      - name: Cache tox env
        uses: actions/cache@v3
        with:
          path: .tox
          key: tox-cache-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('galaxy root/requirements.txt') }}-unit
      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get -y install ffmpeg
      - name: Install tox
        run: pip install tox
      - name: Run tests
        run: tox -e unit-coverage
        working-directory: 'galaxy root'
      - uses: codecov/codecov-action@v3
        with:
          flags: py-unit
          working-directory: 'galaxy root'
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Unit test results (${{ matrix.python-version }})
          path: 'galaxy root/run_unit_tests.html'
